name: johannes
favicon: null
layout_spectrum: 0.18700724584050477
typography_spectrum: 0.03804411552846432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.16000534128397703
  lightness: 0.7575294657144696
  saturation: 0.25476816412992775
  rhythmicContrast: 0.4542562775313854
purpose: []
